### ISSUE TITLE
st_join no longer renames geometry column into "geometry"

### ISSUE THREAD

**Issue by edzer** [lcgodoy/smile#12]
On a reverse dependency check, `sf` release candidate now causes an error `smile`, caused by https://github.com/r-spatial/sf/pull/2327 :
```r
> pred_lsoa <- predict_spm(x = liv_lsoa, spm_obj = fit_msoa, id_var = "lsoa11cd")
Error in `[.data.frame`(x, i) : undefined columns selected
Calls: predict_spm -> predict_spm.sf -> [ -> [.sf -> [ -> [.data.frame
```
which is caused by the line
```r
pred_grid <- spm_obj$call_data$grid["geometry"]
```
where
```r
Browse[3]> names(spm_obj$call_data$grid)
[1] "msoa11cd" "out_grid"
```
because on creation, the geometry column is no longer renamed and keeps its original name, created in `spd.R`. Shall I try to write a PR solving this?

**Comment by edzer** [comment]
I'm planning to submit the `sf` causing this error in `smile` in the next few days.

**Comment by lcgodoy** [comment]
The PR would be very welcome, and I’ll be happy to help in any way you need.

**Comment by edzer** [comment]
See above, the PR is there.

**Comment by edzer** [comment]
Thanks; `sf` has now been submitted to CRAN.
