### ISSUE TITLE
Undocumented variance approximation methods

### ISSUE THREAD

**Issue by JsLth** [lcgodoy/smile#9]
Hi, thanks for the great package! It's looking awesome so far!

I noticed that there are two methods for the uncertainty function `ai_var` that are not documented in the vignette or function reference, `LB` and `MI2`. I'm can figure that `MI2` is an alternative way to calculate Moran's I, but I'm completely puzzled as to what `LB` is. Is it possible to add an explanation to both of them?

https://github.com/lcgodoy/smile/blob/da1194b137fc6a41e44f9e0aad6080796581393c/R/sai.R#L220-L240

**Comment by lcgodoy** [comment]
Hi @JsLth,

Thank you for your message.

We are writing a paper about these approximations, and the reviewing process is longer than expected. I was waiting for the paper to be published to enhance the documentation.

Those are approximations for the variance of the interpolated values. “CS” is an upper bound of such variance based on the Cauchy-Schwartz inequality and tends to be an overestimate (thus, it can be used as a “conservative” estimate). “MI” multiplies the “CS” upper bound by the “Global” Moran’s I, which is between -1 and 1 and, consequently, is always smaller or equal to the estimate provided by the “CS” method. “LB,” on the other hand, is a lower bound for the variance of the interpolated value. “MI2” is still under development. 

I expect to resume the package development in the upcoming weeks and include some Bayesian methods to deal with this problem.

I hope this helps.
Best,
Lucas.
